<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMMqFcOz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMMqFcOz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMMqFcOz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMMqFcOz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMMqFcOz\App_KernelDevDebugContainer([
    'container.build_hash' => 'MMqFcOz',
    'container.build_id' => '7b2cc8ca',
    'container.build_time' => 1587902266,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMMqFcOz');
