<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9SiTugD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9SiTugD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9SiTugD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9SiTugD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9SiTugD\App_KernelDevDebugContainer([
    'container.build_hash' => '9SiTugD',
    'container.build_id' => '2e0ebbf8',
    'container.build_time' => 1584887949,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9SiTugD');
