<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCyGmYcX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCyGmYcX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCyGmYcX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCyGmYcX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCyGmYcX\App_KernelDevDebugContainer([
    'container.build_hash' => 'CyGmYcX',
    'container.build_id' => '66389913',
    'container.build_time' => 1587910643,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCyGmYcX');
